# -- General Settings --
set -g default-terminal "screen-256color"  # More compatible than tmux-256color
set -ga terminal-overrides ",xterm-256color:Tc"
setw -g pane-base-index 1
set -g base-index 1

# -- Plugins --
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g mouse on

# -- Persistence Settings --
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
# Disable 'boot' since we are using the Systemd method above (it's more stable)
set -g @continuum-boot 'off' 

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
